package day14

val lookup_0 = mapOf(
    Pair("PMVMQ", Pair("PMVMQ", 3L)),
    Pair("BTQL", Pair("BTQL", 4L)),
    Pair("HDJB", Pair("HDJB", 5L)),
    Pair("BGPF", Pair("BGPF", 7L)),
    Pair("QHFKR", Pair("QHFKR", 3L)),
    Pair("TPXCK", Pair("TPXCK", 1L)),
    Pair("XFGH", Pair("XFGH", 4L)),
    Pair("GRNC", Pair("GRNC", 4L)),
    Pair("GRDNT", Pair("GRDNT", 1L)),
    Pair("LCHZ", Pair("LCHZ", 5L)),
    Pair("LWDP", Pair("LWDP", 9L)),
    Pair("RQFRT", Pair("RQFRT", 5L)),
    Pair("SDLJ", Pair("SDLJ", 6L)),
    Pair("GCZLZ", Pair("GCZLZ", 1L)),
    Pair("FBRG", Pair("FBRG", 1L)),
    Pair("WXGV", Pair("WXGV", 5L)),
    Pair("WDXT", Pair("WDXT", 6L)),
    Pair("FCNPB", Pair("FCNPB", 5L)),
    Pair("KLRB", Pair("KLRB", 9L)),
    Pair("GLZH", Pair("GLZH", 4L)),
    Pair("SVDX", Pair("SVDX", 5L)),
    Pair("LHFV", Pair("LHFV", 7L)),
    Pair("RSZF", Pair("RSZF", 3L)),
    Pair("TSGR", Pair("TSGR", 6L)),
    Pair("NKHSG", Pair("NKHSG", 5L)),
    Pair("GDXC", Pair("GDXC", 9L)),
    Pair("SKZGB", Pair("SKZGB", 8L)),
    Pair("QZVM", Pair("QZVM", 8L)),
    Pair("FUEL", Pair("FUEL", 1L)),
    Pair("PXKHG", Pair("PXKHG", 1L)),
    Pair("VTDQ", Pair("VTDQ", 8L)),
    Pair("FCPC", Pair("FCPC", 1L)),
    Pair("FWGTF", Pair("FWGTF", 8L)),
    Pair("WPZN", Pair("WPZN", 3L)),
    Pair("HWKG", Pair("HWKG", 6L)),
    Pair("XZBJ", Pair("XZBJ", 4L)),
    Pair("CTDRZ", Pair("CTDRZ", 9L)),
    Pair("JTJT", Pair("JTJT", 7L)),
    Pair("BGNLR", Pair("BGNLR", 3L)),
    Pair("HTFL", Pair("HTFL", 4L)),
    Pair("XFGQ", Pair("XFGQ", 6L)),
    Pair("LXQWG", Pair("LXQWG", 8L)),
    Pair("JBXDX", Pair("JBXDX", 9L)),
    Pair("RLNF", Pair("RLNF", 8L)),
    Pair("WNSW", Pair("WNSW", 3L)),
    Pair("SCDS", Pair("SCDS", 2L)),
    Pair("GMRN", Pair("GMRN", 3L)),
    Pair("KBCW", Pair("KBCW", 8L)),
    Pair("PSVLS", Pair("PSVLS", 4L)),
    Pair("MZTVH", Pair("MZTVH", 9L)),
    Pair("HRCG", Pair("HRCG", 5L)),
    Pair("PZPBV", Pair("PZPBV", 3L)),
    Pair("PLCNZ", Pair("PLCNZ", 9L)),
    Pair("ZXNM", Pair("ZXNM", 6L)),
    Pair("TCQW", Pair("TCQW", 8L)),
    Pair("NRFLK", Pair("NRFLK", 4L)),
    Pair("VHJX", Pair("VHJX", 3L)),
    Pair("LSNG", Pair("LSNG", 7L)),
    Pair("ZGWT", Pair("ZGWT", 5L)),
    Pair("MHRVG", Pair("MHRVG", 6L)),
    Pair("LHVTN", Pair("LHVTN", 5L))
)

val data_0 = mapOf(
    Pair(Pair("PMVMQ", 3L), listOf(Pair("LHFV", 8L))),
    Pair(Pair("BTQL", 4L), listOf(Pair("ZXNM", 2L), Pair("PSVLS", 1L), Pair("GRDNT", 4L), Pair("GLZH", 26L), Pair("VHJX", 3L), Pair("BGPF", 16L), Pair("LHVTN", 1L))),
    Pair(Pair("HDJB", 5L), listOf(Pair("NKHSG", 10L), Pair("FCPC", 20L), Pair("GRDNT", 11L))),
    Pair(Pair("BGPF", 7L), listOf(Pair("WPZN", 6L), Pair("LHFV", 1L))),
    Pair(Pair("QHFKR", 3L), listOf(Pair("WDXT", 1L), Pair("PLCNZ", 1L))),
    Pair(Pair("TPXCK", 1L), listOf(Pair("LCHZ", 12L))),
    Pair(Pair("XFGH", 4L), listOf(Pair("LSNG", 11L))),
    Pair(Pair("GRNC", 4L), listOf(Pair("ORE", 195L))),
    Pair(Pair("GRDNT", 1L), listOf(Pair("XFGQ", 8L))),
    Pair(Pair("LCHZ", 5L), listOf(Pair("FBRG", 1L))),
    Pair(Pair("LWDP", 9L), listOf(Pair("XZBJ", 7L), Pair("RSZF", 8L), Pair("SVDX", 9L))),
    Pair(Pair("RQFRT", 5L), listOf(Pair("WDXT", 20L))),
    Pair(Pair("SDLJ", 6L), listOf(Pair("LXQWG", 1L), Pair("GLZH", 1L))),
    Pair(Pair("GCZLZ", 1L), listOf(Pair("XFGH", 4L))),
    Pair(Pair("FBRG", 1L), listOf(Pair("WPZN", 1L))),
    Pair(Pair("WXGV", 5L), listOf(Pair("XZBJ", 19L))),
    Pair(Pair("WDXT", 6L), listOf(Pair("GDXC", 1L))),
    Pair(Pair("FCNPB", 5L), listOf(Pair("WXGV", 1L), Pair("NKHSG", 1L), Pair("LWDP", 2L))),
    Pair(Pair("KLRB", 9L), listOf(Pair("LWDP", 4L), Pair("BGPF", 5L))),
    Pair(Pair("GLZH", 4L), listOf(Pair("GMRN", 1L))),
    Pair(Pair("SVDX", 5L), listOf(Pair("RQFRT", 1L))),
    Pair(Pair("LHFV", 7L), listOf(Pair("HWKG", 2L))),
    Pair(Pair("RSZF", 3L), listOf(Pair("LCHZ", 2L), Pair("JTJT", 13L), Pair("TPXCK", 10L))),
    Pair(Pair("TSGR", 6L), listOf(Pair("MZTVH", 29L))),
    Pair(Pair("NKHSG", 5L), listOf(Pair("NRFLK", 9L), Pair("SVDX", 1L))),
    Pair(Pair("GDXC", 9L), listOf(Pair("ORE", 123L))),
    Pair(Pair("SKZGB", 8L), listOf(Pair("PZPBV", 1L), Pair("PMVMQ", 21L), Pair("GCZLZ", 1L))),
    Pair(Pair("QZVM", 8L), listOf(Pair("GRNC", 3L), Pair("GDXC", 5L))),
    Pair(Pair("FUEL", 1L), listOf(Pair("VTDQ", 6L), Pair("TCQW", 13L), Pair("FCNPB", 3L), Pair("PSVLS", 48L), Pair("RLNF", 3L), Pair("BTQL", 73L), Pair("MHRVG", 5L), Pair("BGPF", 26L), Pair("HDJB", 26L), Pair("XFGQ", 5L), Pair("HTFL", 6L))),
    Pair(Pair("PXKHG", 1L), listOf(Pair("QZVM", 5L), Pair("JTJT", 2L))),
    Pair(Pair("VTDQ", 8L), listOf(Pair("LSNG", 3L), Pair("PMVMQ", 1L))),
    Pair(Pair("FCPC", 1L), listOf(Pair("XFGH", 31L))),
    Pair(Pair("FWGTF", 8L), listOf(Pair("PSVLS", 9L))),
    Pair(Pair("WPZN", 3L), listOf(Pair("GRNC", 1L))),
    Pair(Pair("HWKG", 6L), listOf(Pair("JBXDX", 16L), Pair("GRNC", 4L))),
    Pair(Pair("XZBJ", 4L), listOf(Pair("SKZGB", 1L), Pair("RSZF", 5L))),
    Pair(Pair("CTDRZ", 9L), listOf(Pair("ORE", 134L))),
    Pair(Pair("JTJT", 7L), listOf(Pair("SVDX", 1L), Pair("TPXCK", 2L))),
    Pair(Pair("BGNLR", 3L), listOf(Pair("RQFRT", 6L), Pair("KBCW", 4L))),
    Pair(Pair("HTFL", 4L), listOf(Pair("KLRB", 12L), Pair("LHFV", 12L))),
    Pair(Pair("XFGQ", 6L), listOf(Pair("GMRN", 2L))),
    Pair(Pair("LXQWG", 8L), listOf(Pair("WNSW", 16L), Pair("SKZGB", 12L))),
    Pair(Pair("JBXDX", 9L), listOf(Pair("NRFLK", 2L), Pair("CTDRZ", 2L))),
    Pair(Pair("RLNF", 8L), listOf(Pair("PZPBV", 1L))),
    Pair(Pair("WNSW", 3L), listOf(Pair("JTJT", 2L), Pair("GCZLZ", 5L))),
    Pair(Pair("SCDS", 2L), listOf(Pair("WXGV", 5L), Pair("LCHZ", 2L))),
    Pair(Pair("GMRN", 3L), listOf(Pair("QHFKR", 1L))),
    Pair(Pair("KBCW", 8L), listOf(Pair("JTJT", 10L), Pair("HRCG", 2L))),
    Pair(Pair("PSVLS", 4L), listOf(Pair("HWKG", 7L))),
    Pair(Pair("MZTVH", 9L), listOf(Pair("WNSW", 7L), Pair("PXKHG", 1L), Pair("BGNLR", 3L))),
    Pair(Pair("HRCG", 5L), listOf(Pair("TPXCK", 15L), Pair("LHFV", 11L))),
    Pair(Pair("PZPBV", 3L), listOf(Pair("LSNG", 1L), Pair("HWKG", 1L))),
    Pair(Pair("PLCNZ", 9L), listOf(Pair("BGPF", 7L))),
    Pair(Pair("ZXNM", 6L), listOf(Pair("ZGWT", 1L))),
    Pair(Pair("TCQW", 8L), listOf(Pair("NKHSG", 26L), Pair("LHFV", 1L), Pair("JTJT", 2L), Pair("WXGV", 26L), Pair("SDLJ", 6L), Pair("KLRB", 1L), Pair("TSGR", 1L))),
    Pair(Pair("NRFLK", 4L), listOf(Pair("ORE", 154L))),
    Pair(Pair("VHJX", 3L), listOf(Pair("GMRN", 1L))),
    Pair(Pair("LSNG", 7L), listOf(Pair("QZVM", 5L), Pair("GDXC", 3L))),
    Pair(Pair("ZGWT", 5L), listOf(Pair("WNSW", 5L))),
    Pair(Pair("MHRVG", 6L), listOf(Pair("QHFKR", 6L), Pair("PZPBV", 8L), Pair("FBRG", 10L), Pair("FWGTF", 13L), Pair("LHVTN", 1L), Pair("SCDS", 4L), Pair("VHJX", 8L), Pair("TSGR", 7L))),
    Pair(Pair("LHVTN", 5L), listOf(Pair("GLZH", 12L)))
)

val lookup_1 = mapOf(
    Pair("A", Pair("A", 10L)),
    Pair("B", Pair("B", 1L)),
    Pair("C", Pair("C", 1L)),
    Pair("D", Pair("D", 1L)),
    Pair("E", Pair("E", 1L)),
    Pair("FUEL", Pair("FUEL", 1L))
)

val data_1 = mapOf(
    Pair(Pair("A", 10L), listOf(Pair("ORE", 10L))),
    Pair(Pair("B", 1L), listOf(Pair("ORE", 1L))),
    Pair(Pair("C", 1L), listOf(Pair("A", 7L), Pair("B", 1L))),
    Pair(Pair("D", 1L), listOf(Pair("A", 7L), Pair("C", 1L))),
    Pair(Pair("E", 1L), listOf(Pair("A", 7L), Pair("D", 1L))),
    Pair(Pair("FUEL", 1L), listOf(Pair("A", 7L), Pair("E", 1L)))
)

val lookup_2 = mapOf(
    Pair("A", Pair("A", 2L)),
    Pair("B", Pair("B", 3L)),
    Pair("C", Pair("C", 5L)),
    Pair("AB", Pair("AB", 1L)),
    Pair("BC", Pair("BC", 1L)),
    Pair("CA", Pair("CA", 1L)),
    Pair("FUEL", Pair("FUEL", 1L))
)

val data_2 = mapOf(
    Pair(Pair("A", 2L), listOf(Pair("ORE", 9L))),
    Pair(Pair("B", 3L), listOf(Pair("ORE", 8L))),
    Pair(Pair("C", 5L), listOf(Pair("ORE", 7L))),
    Pair(Pair("AB", 1L), listOf(Pair("A", 3L), Pair("B", 4L))),
    Pair(Pair("BC", 1L), listOf(Pair("B", 5L), Pair("C", 7L))),
    Pair(Pair("CA", 1L), listOf(Pair("C", 4L), Pair("A", 1L))),
    Pair(Pair("FUEL", 1L), listOf(Pair("AB", 2L), Pair("BC", 3L), Pair("CA", 4L)))
)

val lookup_4 = mapOf(
    Pair("NZVS", Pair("NZVS", 5L)),
    Pair("DCFZ", Pair("DCFZ", 6L)),
    Pair("FUEL", Pair("FUEL", 1L)),
    Pair("QDVJ", Pair("QDVJ", 9L)),
    Pair("PSHF", Pair("PSHF", 7L)),
    Pair("HKGWZ", Pair("HKGWZ", 5L)),
    Pair("XJWVT", Pair("XJWVT", 2L)),
    Pair("GPVTF", Pair("GPVTF", 2L)),
    Pair("KHKGT", Pair("KHKGT", 8L))
)

val data_4 = mapOf(
    Pair(Pair("NZVS", 5L), listOf(Pair("ORE", 157L))),
    Pair(Pair("DCFZ", 6L), listOf(Pair("ORE", 165L))),
    Pair(Pair("FUEL", 1L), listOf(Pair("XJWVT", 44L), Pair("KHKGT", 5L), Pair("QDVJ", 1L), Pair("NZVS", 29L), Pair("GPVTF", 9L), Pair("HKGWZ", 48L))),
    Pair(Pair("QDVJ", 9L), listOf(Pair("HKGWZ", 12L), Pair("GPVTF", 1L), Pair("PSHF", 8L))),
    Pair(Pair("PSHF", 7L), listOf(Pair("ORE", 179L))),
    Pair(Pair("HKGWZ", 5L), listOf(Pair("ORE", 177L))),
    Pair(Pair("XJWVT", 2L), listOf(Pair("DCFZ", 7L), Pair("PSHF", 7L))),
    Pair(Pair("GPVTF", 2L), listOf(Pair("ORE", 165L))),
    Pair(Pair("KHKGT", 8L), listOf(Pair("DCFZ", 3L), Pair("NZVS", 7L), Pair("HKGWZ", 5L), Pair("PSHF", 10L)))
)


val lookup_5 = mapOf(
    Pair("CNZTR", Pair("CNZTR", 8L)),
    Pair("PLWSL", Pair("PLWSL", 4L)),
    Pair("BHXH", Pair("BHXH", 4L)),
    Pair("BMBT", Pair("BMBT", 6L)),
    Pair("FUEL", Pair("FUEL", 1L)),
    Pair("FHTLT", Pair("FHTLT", 6L)),
    Pair("ZLQW", Pair("ZLQW", 6L)),
    Pair("ZDVW", Pair("ZDVW", 1L)),
    Pair("WPTQ", Pair("WPTQ", 4L)),
    Pair("KTJDG", Pair("KTJDG", 9L)),
    Pair("XMNCP", Pair("XMNCP", 2L)),
    Pair("XDBXC", Pair("XDBXC", 2L)),
    Pair("XCVML", Pair("XCVML", 5L)),
    Pair("MZWV", Pair("MZWV", 7L)),
    Pair("VRPVC", Pair("VRPVC", 7L)),
    Pair("RJRHP", Pair("RJRHP", 6L)),
    Pair("LTCX", Pair("LTCX", 5L))
)

val data_5 = mapOf(
    Pair(Pair("CNZTR", 8L), listOf(Pair("ORE", 171L))),
    Pair(Pair("PLWSL", 4L), listOf(Pair("ZLQW", 7L),Pair("BMBT", 3L),Pair("XCVML", 9L),Pair("XMNCP", 26L),Pair("WPTQ", 1L),Pair("MZWV", 2L),Pair("RJRHP", 1L))),
    Pair(Pair("BHXH", 4L), listOf(Pair("ORE", 114L))),
    Pair(Pair("BMBT", 6L), listOf(Pair("VRPVC", 14L))),
    Pair(Pair("FUEL", 1L),listOf(Pair("BHXH", 6L),Pair("KTJDG", 18L),Pair("WPTQ", 12L),Pair("PLWSL", 7L),Pair("FHTLT", 31L),Pair("ZDVW", 37L))),
    Pair(Pair("FHTLT", 6L),listOf(Pair("WPTQ", 6L),Pair("BMBT", 2L),Pair("ZLQW", 8L),Pair("KTJDG", 18L),Pair("XMNCP", 1L),Pair("MZWV", 6L),Pair("RJRHP", 1L))),
    Pair(Pair("ZLQW", 6L), listOf(Pair("XDBXC", 15L), Pair("LTCX", 2L), Pair("VRPVC", 1L))),
    Pair(Pair("ZDVW", 1L),listOf(Pair("WPTQ", 13L),Pair("LTCX", 10L),Pair("RJRHP", 3L),Pair("XMNCP", 14L),Pair("MZWV", 2L),Pair("ZLQW", 1L))),
    Pair(Pair("WPTQ", 4L), listOf(Pair("BMBT", 5L))),
    Pair(Pair("KTJDG", 9L), listOf(Pair("ORE", 189L))),
    Pair(Pair("XMNCP", 2L), listOf(Pair("MZWV", 1L), Pair("XDBXC", 17L), Pair("XCVML", 3L))),
    Pair(Pair("XDBXC", 2L), listOf(Pair("VRPVC", 12L), Pair("CNZTR", 27L))),
    Pair(Pair("XCVML", 5L), listOf(Pair("KTJDG", 15L), Pair("BHXH", 12L))),
    Pair(Pair("MZWV", 7L), listOf(Pair("BHXH", 3L), Pair("VRPVC", 2L))),
    Pair(Pair("VRPVC", 7L), listOf(Pair("ORE", 121L))),
    Pair(Pair("RJRHP", 6L), listOf(Pair("XCVML", 7L))),
    Pair(Pair("LTCX", 5L), listOf(Pair("BHXH", 5L), Pair("VRPVC", 4L)))
)
